-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户表
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account TEXT UNIQUE NOT NULL,
  nickname TEXT NOT NULL DEFAULT '',
  avatar TEXT DEFAULT '',
  bio TEXT DEFAULT '',
  user_type SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 分类表
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type SMALLINT DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 视频表
CREATE TABLE IF NOT EXISTS videos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  tags TEXT[] DEFAULT '{}',
  cover_url TEXT DEFAULT '',
  video_url TEXT DEFAULT '',
  duration INTEGER DEFAULT 0,
  category_id INTEGER REFERENCES categories(id),
  view_count INTEGER DEFAULT 0,
  like_count INTEGER DEFAULT 0,
  comment_count INTEGER DEFAULT 0,
  favorite_count INTEGER DEFAULT 0,
  uploader_id UUID REFERENCES profiles(id),
  audit_status SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 直播间表
CREATE TABLE IF NOT EXISTS live_rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  category_id INTEGER REFERENCES categories(id),
  cover TEXT DEFAULT '',
  stream_key TEXT UNIQUE NOT NULL,
  push_url TEXT DEFAULT '',
  pull_url TEXT DEFAULT '',
  anchor_id UUID REFERENCES profiles(id),
  online_count INTEGER DEFAULT 0,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 评论表
CREATE TABLE IF NOT EXISTS comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content TEXT NOT NULL,
  user_id UUID REFERENCES profiles(id),
  video_id UUID REFERENCES videos(id),
  parent_id UUID DEFAULT NULL,
  like_count INTEGER DEFAULT 0,
  is_top BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 弹幕表
CREATE TABLE IF NOT EXISTS danmaku (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content TEXT NOT NULL,
  color TEXT DEFAULT '#FFFFFF',
  position SMALLINT DEFAULT 0,
  user_id UUID REFERENCES profiles(id),
  target_id UUID NOT NULL,
  target_type SMALLINT DEFAULT 0,
  video_time INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 关注表
CREATE TABLE IF NOT EXISTS follows (
  follower_id UUID REFERENCES profiles(id),
  following_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (follower_id, following_id)
);

-- 视频点赞表
CREATE TABLE IF NOT EXISTS video_likes (
  video_id UUID REFERENCES videos(id),
  user_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (video_id, user_id)
);

-- 视频收藏表
CREATE TABLE IF NOT EXISTS video_favorites (
  video_id UUID REFERENCES videos(id),
  user_id UUID REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (video_id, user_id)
);

-- 观看历史表
CREATE TABLE IF NOT EXISTS watch_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id),
  video_id UUID REFERENCES videos(id),
  progress INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (user_id, video_id)
);

-- 敏感词表
CREATE TABLE IF NOT EXISTS sensitive_words (
  id SERIAL PRIMARY KEY,
  word TEXT UNIQUE NOT NULL,
  level SMALLINT DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 初始化分类数据
INSERT INTO categories (name, type, sort_order) VALUES
('推荐', 0, 0),
('游戏', 0, 1),
('音乐', 0, 2),
('影视', 0, 3),
('科技', 0, 4),
('生活', 0, 5),
('游戏直播', 1, 1),
('娱乐直播', 1, 2),
('学习直播', 1, 3)
ON CONFLICT DO NOTHING;

-- 初始化敏感词
INSERT INTO sensitive_words (word, level) VALUES
('脏话1', 1),
('脏话2', 2),
('违禁词', 3)
ON CONFLICT DO NOTHING;

-- 启用RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE danmaku ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;

-- RLS策略
CREATE POLICY "公开读取用户资料" ON profiles FOR SELECT USING (true);
CREATE POLICY "用户可修改自己资料" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "公开读取视频" ON videos FOR SELECT USING (audit_status = 1 AND status = 0);
CREATE POLICY "创作者可创建视频" ON videos FOR INSERT WITH CHECK (auth.uid() = uploader_id);
CREATE POLICY "创作者可修改自己视频" ON videos FOR UPDATE USING (auth.uid() = uploader_id);

CREATE POLICY "公开读取直播间" ON live_rooms FOR SELECT USING (true);
CREATE POLICY "主播可创建直播间" ON live_rooms FOR INSERT WITH CHECK (auth.uid() = anchor_id);
CREATE POLICY "主播可修改自己直播间" ON live_rooms FOR UPDATE USING (auth.uid() = anchor_id);

CREATE POLICY "公开读取评论" ON comments FOR SELECT USING (true);
CREATE POLICY "登录用户可发表评论" ON comments FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "公开读取弹幕" ON danmaku FOR SELECT USING (true);
CREATE POLICY "登录用户可发弹幕" ON danmaku FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "用户可查看自己关注" ON follows FOR SELECT USING (auth.uid() = follower_id);
CREATE POLICY "用户可关注他人" ON follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "用户可取消关注" ON follows FOR DELETE USING (auth.uid() = follower_id);

CREATE POLICY "用户可查看自己点赞" ON video_likes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可点赞" ON video_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可取消点赞" ON video_likes FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "用户可查看自己收藏" ON video_favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可收藏" ON video_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可取消收藏" ON video_favorites FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "用户可查看自己历史" ON watch_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可添加历史" ON watch_history FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可更新自己历史" ON watch_history FOR UPDATE USING (auth.uid() = user_id);